### ISSUE TITLE
how can i transfer changes to another node

### ISSUE THREAD

**Issue by mccoysc** [orbitdb/crdts#15]
how can i transfer changes to another node to sync

**Comment by RichardLitt** [comment]
@aphelionz Want to take a stab?

**Comment by haadcode** [comment]
This module doesn't handle data structure synchronization in any way. It's up to the user to decide how/where to transfer changes or updates to the CRDTs. For example, [ipfs-log](https://github.com/orbitdb/ipfs-log) can be used to add a transport mechanism for synchronizing data between different nodes (which is what we do in OrbitDB).
